// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pillow.Infrastructure.Data;

namespace Pillow.Infrastructure.Data.Migrations
{
    [DbContext(typeof(BookContext))]
    [Migration("20210703190949_TitleAddToTrack")]
    partial class TitleAddToTrack
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Pillow.ApplicationCore.Entities.BookAggregate.Book", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<int>("AccessLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Author")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CoverUri")
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<long>("Likes")
                        .HasColumnType("bigint");

                    b.Property<long>("Preorders")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Code");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Pillow.ApplicationCore.Entities.BookAggregate.BookTag", b =>
                {
                    b.Property<string>("BookCode")
                        .HasColumnType("text");

                    b.Property<string>("TagCode")
                        .HasColumnType("text");

                    b.HasKey("BookCode", "TagCode");

                    b.HasIndex("TagCode");

                    b.ToTable("BookTag");
                });

            modelBuilder.Entity("Pillow.ApplicationCore.Entities.BookAggregate.Track", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("BookCode")
                        .HasColumnType("text");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasBackgroundMusic")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTrailer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Code");

                    b.HasIndex("BookCode");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("Pillow.ApplicationCore.Entities.NotificationTokenAggregate.NotificationToken", b =>
                {
                    b.Property<string>("Token")
                        .HasMaxLength(178)
                        .HasColumnType("character varying(178)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("PlatformKind")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.HasKey("Token");

                    b.ToTable("NotificationTokens");
                });

            modelBuilder.Entity("Pillow.ApplicationCore.Entities.SubscriptionAggregate.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime>("CancellationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ExpiredDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("OriginalPurchaseDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ProductId")
                        .HasColumnType("text");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ReceiptData")
                        .HasColumnType("text");

                    b.Property<string>("UserAccountUserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountUserName");

                    b.ToTable("Subscription");
                });

            modelBuilder.Entity("Pillow.ApplicationCore.Entities.TagAggregate.Tag", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Code");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Pillow.ApplicationCore.Entities.UserAccountAggregate.FavoriteBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("BookCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserAccountUserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BookCode");

                    b.HasIndex("UserAccountUserName");

                    b.ToTable("FavoriteBooks");
                });

            modelBuilder.Entity("Pillow.ApplicationCore.Entities.UserAccountAggregate.PreorderBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("BookCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserAccountUserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BookCode");

                    b.HasIndex("UserAccountUserName");

                    b.ToTable("PreorderBook");
                });

            modelBuilder.Entity("Pillow.ApplicationCore.Entities.UserAccountAggregate.UserAccount", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("UserName");

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("Pillow.ApplicationCore.Entities.BookAggregate.BookTag", b =>
                {
                    b.HasOne("Pillow.ApplicationCore.Entities.BookAggregate.Book", "Book")
                        .WithMany("BookTag")
                        .HasForeignKey("BookCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pillow.ApplicationCore.Entities.TagAggregate.Tag", "Tag")
                        .WithMany("BookTag")
                        .HasForeignKey("TagCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Pillow.ApplicationCore.Entities.BookAggregate.Track", b =>
                {
                    b.HasOne("Pillow.ApplicationCore.Entities.BookAggregate.Book", "Book")
                        .WithMany("Tracks")
                        .HasForeignKey("BookCode");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Pillow.ApplicationCore.Entities.SubscriptionAggregate.Subscription", b =>
                {
                    b.HasOne("Pillow.ApplicationCore.Entities.UserAccountAggregate.UserAccount", "UserAccount")
                        .WithMany()
                        .HasForeignKey("UserAccountUserName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("Pillow.ApplicationCore.Entities.UserAccountAggregate.FavoriteBook", b =>
                {
                    b.HasOne("Pillow.ApplicationCore.Entities.BookAggregate.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pillow.ApplicationCore.Entities.UserAccountAggregate.UserAccount", "UserAccount")
                        .WithMany("Favorites")
                        .HasForeignKey("UserAccountUserName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("Pillow.ApplicationCore.Entities.UserAccountAggregate.PreorderBook", b =>
                {
                    b.HasOne("Pillow.ApplicationCore.Entities.BookAggregate.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pillow.ApplicationCore.Entities.UserAccountAggregate.UserAccount", "UserAccount")
                        .WithMany("Preorders")
                        .HasForeignKey("UserAccountUserName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("Pillow.ApplicationCore.Entities.BookAggregate.Book", b =>
                {
                    b.Navigation("BookTag");

                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("Pillow.ApplicationCore.Entities.TagAggregate.Tag", b =>
                {
                    b.Navigation("BookTag");
                });

            modelBuilder.Entity("Pillow.ApplicationCore.Entities.UserAccountAggregate.UserAccount", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("Preorders");
                });
#pragma warning restore 612, 618
        }
    }
}
