version: '3.7'

services:
  cron:
    image: sibilica/scheduler:version-1.0.11
    build:
      context: .
      dockerfile: cron/Dockerfile
    networks:
      - app-network
      
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - reverseproxy

  reverseproxy:
    image: nginx:alpine
    restart: always
    depends_on:
      - fluent-bit
      - pillowpublicapi
      - promocodeapi
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx:/start
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    command: /start/run_nginx.sh
    networks:
      - app-network
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: nginx.logs

  fluent-bit:
    container_name: fluent-bit
    image: fluent/fluent-bit
    ports:
      - 24224:24224
      - 24224:24224/udp
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./fluent-bit/parsers.conf:/fluent-bit/parsers/parsers.conf
    networks:
      - app-network
    
  pillowpublicapi:
    image: sibilica/pillowpublicapi:version-1.1.2
    build:
      context: .
      dockerfile: src/BookService/PublicApi/Dockerfile
    depends_on:
      - pillow.db
      - pillow.db.identity
    environment:
      - ASPNETCORE_URLS=http://+:80
      - JWTToken:AccessTokenExpirationMinutes=15
      - JWTToken:RefreshTokenExpirationDays=30
      - UseSwagger=false
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    networks:
      - app-network

  promocodeapi:
    image: sibilica/promocodeapi:version-1.1.2
    build:
      context: .
      dockerfile: src/PromoCode/PromoCode.API/Dockerfile
    depends_on:
      - pillow.db
    environment:
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    networks:
      - app-network
      
  pillow.db:
    image: postgres:13.2-alpine
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  pillow.db.identity:
    image: postgres:13.2-alpine
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network
      
volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /root/sites/renew_cert/views/
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /root/sites/renew_cert/dhparam/
      o: bind
      
networks:
  app-network:
    driver: bridge