// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PromoCode.API.Infrastructure;

namespace PromoCode.API.Infrastructure.Migrations
{
    [DbContext(typeof(PromoCodeContext))]
    [Migration("20211114122023_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Npgsql:CollationDefinition:case_insensitive", "und-u-ks-level2,und-u-ks-level2,icu,False")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("PromoCode.API.Model.AppliedPromoCodeItem", b =>
                {
                    b.Property<string>("PromoCode")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("PromoCode", "UserName");

                    b.ToTable("AppliedPromoCodes");
                });

            modelBuilder.Entity("PromoCode.API.Model.PromoCodeItem", b =>
                {
                    b.Property<string>("PromoCode")
                        .HasColumnType("text")
                        .UseCollation("case_insensitive");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("Limit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(-1);

                    b.Property<string>("SubscriptionsGroup")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("PromoCode");

                    b.ToTable("PromoCode");
                });

            modelBuilder.Entity("PromoCode.API.Model.AppliedPromoCodeItem", b =>
                {
                    b.HasOne("PromoCode.API.Model.PromoCodeItem", "PromoCodeItem")
                        .WithMany("AppliedItems")
                        .HasForeignKey("PromoCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PromoCodeItem");
                });

            modelBuilder.Entity("PromoCode.API.Model.PromoCodeItem", b =>
                {
                    b.Navigation("AppliedItems");
                });
#pragma warning restore 612, 618
        }
    }
}
